ANGELONE_API_KEY=QQuFfWHj
ANGELONE_CLIENT_CODE=P487651
ANGELONE_SECRET_KEY=0506
#ANGELONE_SECRET_KEY=4b757c67-f818-4d37-b4fb-9ad0c4d6abf7
ANGELONE_TOTP_SECRET=VQNYG7CV72C2S35YJ2SJJRRCAQ
TELEGRAM_BOT_TOKEN=7809511890:AAEENJpQBNhT8wQnlEi7MSsaHwq8qd1QYPU
TELEGRAM_CHAT_ID=1230484573
